### ISSUE TITLE
演習問題で使うDATAフォルダについて

### ISSUE THREAD

**Issue by inu-noob** [inu-noob/DataDriven_SuzukiLab#6]
演習問題で使用するフォルダ([DATA](https://github.com/dynamicslab/databook_python/tree/master/DATA))をこのリポジトリに追加する方法ってご存知ですか？自分なりに調べてみたもののできる気がしなかったのでもし可能でしたらお願いしたいです．

**Comment by sho7014** [comment]
ローカルで DATA フォルダつくって、そこになんでも良いのでファイル (test.mdとか) 入れて、このファイルをプッシュすれば DATA フォルダも自動でつくられるはずです
